services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"

  blackbox-exporter:
    image: prom/blackbox-exporter:latest
    container_name: blackbox-exporter
    ports:
      - "9115:9115"
    volumes:
      - ./blackbox/blackbox.yml:/etc/blackbox_exporter/config.yml:ro
    command:
      - "--config.file=/etc/blackbox_exporter/config.yml"

  altice-exporter:
    build: ./altice-exporter
    container_name: altice-exporter
    ports:
      - "127.0.0.1:9876:9876"
    command:
      - "--device.type=GR241AG"
      - "--device.hostname=192.168.1.254:22"
      - "--device.username=${ALTICE_USERNAME}"
      - "--device.password=${ALTICE_PASSWORD}"
      - "--web.listen-address=:9876"
    restart: unless-stopped

volumes:
  prometheus_data:
  grafana_data:
